#:schema node_modules/wrangler/config-schema.json
name = "singbox-sublink-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "4e313b98eac4491ea8af5e07f79afd47" }
]

[assets]
directory = "./public"
